#!/usr/bin/bash
 
TZ=GMT-7 date > /home/fetel/date

#FOR EXAM
rm -rf /home/fetel/lab /home/fetel/book

rm -rf /home/fetel/xv6-labs-2022
mkdir -p /home/fetel/exam
cp /opt/setup/exam*.gpg /home/fetel/exam

#cp /opt/setup/xv6-labs-2022.tar /home/fetel/xv6-labs-2022.tar
#su fetel
#cd ~
#tar xf ~/xv6-labs-2022.tar

tar xf /opt/setup/xv6-labs-2022.tar -C /home/fetel/
chown -R fetel /home/fetel/xv6-labs-2022
